SudentInstractor/Models/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SudentInstractor.Models
{
    public class Student
    {

        [Display(Name = "Student Id")]
        [Required(ErrorMessage = "Required Id")]
        public int StudentID { get; set; }


        [Display(Name = "First Name")]
        [Required(ErrorMessage = "Enter your First  Name")]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "Enter your Last  Name")]
        public string LastName { get; set; }

        [Required(ErrorMessage ="Provide your email address")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required(ErrorMessage = "Provide your phone number")]
        [DataType(DataType.PhoneNumber)]
        public string Phone { get; set; }
        
        public List<StudentCourse> StudentCourses { set; get; }
    }


}

SudentInstractor/Controllers/StudentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SudentInstractor.Data;
using SudentInstractor.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SudentInstractor.Controllers
{
    public class StudentController : Controller
    {
        private readonly CollegeDbCotext _dbc = new CollegeDbCotext();


        public IActionResult Index()
        {
            List<Student> students = _dbc.Students.ToList();

            return View(students);
        }

        public IActionResult Details(int id)
        {
            Student student = _dbc.Students.Where(s => s.StudentID == id).FirstOrDefault();
            if (student == null)
            {
                return HttpNotFound();
            }
            List<Course> courses = _dbc.StudentCourses
                .Where(sc => sc.StudentId == id)
                .Select(c => c.Course)
                .ToList();
             ViewBag.Courses = courses;
            return View(student);
        }

        private IActionResult HttpNotFound()
        {
            throw new NotImplementedException();
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Courses = _dbc.Courses.ToList();

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Student student)
        {

            if (ModelState.IsValid)
            {
                student.StudentID = _dbc.Students.Last().StudentID + 1;
                _dbc.Students.Add(student);
                _dbc.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(student);
        }

        public IActionResult Edit(int id)
        {
            
            Student std = _dbc.Students.Where(s => s.StudentID == id).FirstOrDefault();

            List<Course> courses = _dbc.StudentCourses
                .Where(sc => sc.StudentId == id)
                .Select(c => c.Course)
                .ToList();

            ViewBag.Courses = courses;

            ViewBag.AvailableCourses = _dbc.Courses
                .Except(courses)
                .ToList();

            return View(std);
        }
        [HttpPost,ActionName("Edit")]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public ActionResult Edit(Student std)
        {
          

            try
            {
                if (ModelState.IsValid)
                {

                    var student = _dbc.Students.Where(s => s.StudentID == std.StudentID).FirstOrDefault();
                    if (std != null)
                    {
                        student.StudentID = std.StudentID;
                        student.FirstName = std.FirstName;
                        student.LastName = std.LastName;
                        student.Email = std.Email;
                        student.Phone = std.Phone;

                        _dbc.Students.Remove(student);
                        _dbc.Students.Add(std);
                        _dbc.SaveChanges();
                    }
                    return RedirectToAction("Index");
                }
            }
            catch(DataMisalignedException)
            {

                ModelState.AddModelError("", "Unable to save changes. Try again");
            }

            return View(std);
        }



        [HttpGet]
        public IActionResult Delete(int? id, bool? saveChangesError = false)

        {
            if (id == null)
            {
                return NotFound();
            }


            if (saveChangesError.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "Delete failed. Try again.";
            }

            Student st = _dbc.Students.Where(s => s.StudentID == id).FirstOrDefault();

            if (st == null)
            {
                return HttpNotFound();
            }

            return View(st);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            Student st = _dbc.Students.Where(s => s.StudentID == id).FirstOrDefault();
            _dbc.Students.Find(id);
            _dbc.Students.Remove(st);
            _dbc.SaveChanges();

            return RedirectToAction("Index");

        }

        protected override void Dispose(bool disposing)
        {
            _dbc.Dispose();
            base.Dispose(disposing);
        }
    }
}

SudentInstractor/Controllers/StudentCourseController.cs
using Microsoft.AspNetCore.Mvc;
using SudentInstractor.Data;
using SudentInstractor.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SudentInstractor.Controllers
{
    public class StudentCourseController : Controller
    {
        private readonly CollegeDbCotext _dbc = new CollegeDbCotext();


        public IActionResult AddCourse(int studentId, int courseId)
        {
            

            _dbc.StudentCourses
                .Add(new StudentCourse
                {
                    StudentId= studentId,
                    CourseId = courseId
                });

            _dbc.SaveChanges();

            return RedirectToAction("Edit", "Student", new { id = studentId });

        }
      
        }


    }

SudentInstractor/Views/Student/Create.cshtml
@model SudentInstractor.Models.Student

@{
    ViewData["Title"] = "Create";
}



<h4>Register  new Student</h4>


    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                @*<div class="form-group">
                    ID
                    <label asp-for="StudentID" class="control-label"></label>
                    <input asp-for="StudentID" class="form-control" />
                    <span asp-validation-for="StudentID" class="text-danger"></span>
                </div*@
                <div class="form-group">
                 
                    <label asp-for="FirstName" class="control-label"></label>
                    <input asp-for="FirstName" class="form-control" />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
                <div class="form-group">
               
                    <label asp-for="LastName" class="control-label"></label>
                    <input asp-for="LastName" class="form-control" />
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Email" class="control-label"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Phone" class="control-label"></label>
                    <input asp-for="Phone" class="form-control" />
                    <span asp-validation-for="Phone" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Register" class="btn btn-primary" />
                </div>
                <div class="form-group">
                    <input type="submit" value="Cancel" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

SudentInstractor/Views/Student/Delete.cshtml
@model SudentInstractor.Models.Student

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this student?</h3>
<div>
    
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StudentID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StudentID)
        </dd>
        <dt class = "col-sm-2">
           
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SudentInstractor/Views/Student/Details.cshtml
@model SudentInstractor.Models.Student

@{
    ViewData["Title"] = "Details";
}



<div>
    <h4>Student Details</h4>
    <hr />
    <dl class="row">
        @*<dt class="col-sm-2">
            ID
            @Html.DisplayNameFor(model => model.StudentID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StudentID)
        </dd>*@
        <dt class="col-sm-2">
      
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
       
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
    </dl>
</div>

<div>

    <dl class="dl-horizontal">
        @foreach (var item in ViewBag.Courses)
        { 
            <dt>Course name</dt>
            <dd>@item.Name</dd>
        }
    </dl>
</div>

<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.StudentID }) |
    <a asp-action="Index">Back to List</a>
</div>

SudentInstractor/Views/Student/Edit.cshtml
@model SudentInstractor.Models.Student

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Student</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">

            <div class="form-group">
                @*<label asp-for="StudentID" class="control-label"></label>*@
                <input type="hidden" asp-for="StudentID" class="form-control" />
                <span asp-validation-for="StudentID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>

        </form>
    </div>
</div>
<div>
<h4>Courses:</h4>
<dl class="dl-horizontal">

    @foreach (var item in ViewBag.Courses)
    {
        <dt>Name: </dt>
        <dd>@item.Name</dd>
    }
   </dl>
</div>
        
    <div>
        <h4>Add Course:</h4>

        @using (Html.BeginForm("AddCourse", "StudentCourse", FormMethod.Post))
        {
            @Html.Hidden("StudentId", Model.StudentID)
            @Html.DropDownList("CourseId",
                 new SelectList(ViewBag.AvailableCourses, "Id", "Name"))

            <input type="submit" value="Add" class="btn btn-default btn-group-sm " />
        }
    </div>
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

SudentInstractor/Views/Student/Index.cshtml
@model IEnumerable<SudentInstractor.Models.Student>

@{
    ViewData["Title"] = "Index";
}

<h1>Students List</h1>

@*<p>
        <a asp-action="Create">Register New</a>
    </p>*@

<p>
    <div class="col-sm-4">
        <a asp-action="Create" class="btn btn-info create"><i class="fa fa-plus"></i> Add New</a>

    </div>
</p>
<table class="table">
    <thead>
        <tr>
            @*<th>
                    Html.DisplayNameFor(model => model.StudentID)
                </th>*@
            <th>

                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>

                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                @*<td>
                        @Html.DisplayFor(modelItem => item.StudentID)
                    </td*@
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Phone)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.StudentID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.StudentID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.StudentID })
                </td>
            </tr>
        }
    </tbody>
</table>